### ISSUE TITLE
Tipster GUI shows with 'least prio' locale

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Tipster#27]
Very weird:
* Open Locale prefs, choose 1st language "English", 2nd "Deutsch"
* Start Tipster

Behold: The tips are English as expected, but the GUI (menus) are "Deutsch"! What?

* Close Tipster
* Open Locale prefs, choose 1st language "English", 2nd "Deutsch", 3rd "Italiano"
* Start Tipster

Uh, uh... Now the GUI is "Italiano"...!

What's going on?

**Comment by janus2** [comment]
I have investigated the problem...
I don't know why but is the Finnish catalog that makes the LocaleRoster default language empty for english as the first language.
This is present in other applications. I have added the Finnish catalog to Weather and I can see the same problem.

Can you try to remove "fi" from LOCALES in the makefile and verify if this is the case?

**Comment by humdingerb** [comment]
I can confirm. Nice detective work... :)
Still... How... Why... Wha...?

**Comment by janus2** [comment]
I am not familiar with the haiku locale implementation... It is a very strange bug!

**Comment by pulkomandy** [comment]
I'm familiar with the implementation, but I agree it is a very strange bug!
Time to build libbe in debug mode and step through the locale kit then. Since this happens with multiple apps its time to bring the issue to haiku bugtracker, right?

**Comment by humdingerb** [comment]
I created a ticket in Haiku's Trac: [#14150](https://dev.haiku-os.org/ticket/14150)

**Comment by jsteinaker** [comment]
I got interested into this. I've just replied to your Trac ticket. To summarize, it seems English and Finnish catalogs are overlapping with each other, because only the last one you generate works (Finnish if you're using the makefile/alphabetic ordering).

I'm running on 64-bit, so no QuickRes for me. Is there any other app for resource inspection? Can you confirm if the 'en' resources are OK on the Tipster binary? If my theory is right, they should be corrupted somehow, and if you regenerate only English using linkcatkeys, Finnish should become corrupt.

**Comment by pulkomandy** [comment]
As far as I know the english language is not bundled as a catalog, it's just the default strings inside the app code.

**Comment by jsteinaker** [comment]
Not sure about the Haiku system apps that use catalogs on separate files, but in case of apps built with haikuporter, `make bindcatkeys` it's just a for loop that calls `linkcatkeys` for every language mentioned in the Makefile, and that includes 'en'.

In fact, if you manually run linkcatkeys with the 'en' locale outputting to a separate catalog file, and you place this catalog in the proper folder, English works again as expected. Same thing if you do this outputting to the binary resources, but in this case, it breaks Finnish.

Default strings are in fact there, but they seem to be used as a last resource. In the example mentioned by humdinger, they work only because there is no other locale selected. The app can't use/find the english catalog, but there isn't any other language selected, so it falls back to the default strings. As soon as he adds another language in preferences, the app sees that as a better option and loads the catalog.

**Comment by thaflo** [comment]
As this issue is not related to Tipster only, it should be closed. There are Tickets in Trac
https://dev.haiku-os.org/ticket/16677
https://dev.haiku-os.org/ticket/14150

**Comment by humdingerb** [comment]
Right. Thanks.
